(()=>{'use strict';
const DB='auron_files_v1',STORE='files',MAX=200*1024*1024;
const $=id=>document.getElementById(id), input=$('fileInput'),drop=$('drop'),list=$('list'),search=$('search'),meta=$('meta'),error=$('error');
let sortDesc=true;
function b64ToBytes(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function bytesToB64(a){const u=new Uint8Array(a),CH=0x8000;let s='';for(let i=0;i<u.length;i+=CH)s+=String.fromCharCode(...u.subarray(i,i+CH));return btoa(s)}
function key(){const raw=sessionStorage.getItem('auron_session_key');if(!raw)throw new Error('Kein aktiver Vault. Öffne zuerst Auron Vault und entsperre den Tresor.');return crypto.subtle.importKey('raw',b64ToBytes(raw),{name:'AES-GCM'},false,['encrypt','decrypt'])}
function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('name','name');s.createIndex('updatedAt','updatedAt')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function tx(mode,fn){return db().then(d=>new Promise((res,rej)=>{const q=d.transaction(STORE,mode).objectStore(STORE);const r=fn(q);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}))}
function all(){return tx('readonly',s=>s.getAll())}
function put(v){return tx('readwrite',s=>s.put(v))}
function remove(id){return tx('readwrite',s=>s.delete(id))}
function fmt(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function encrypt(file){const k=await key(),iv=crypto.getRandomValues(new Uint8Array(12)),buf=await file.arrayBuffer(),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,buf);return{iv:bytesToB64(iv),data,type:file.type||'application/octet-stream',size:file.size}}
async function decrypt(rec){const k=await key(),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(rec.iv)},k,rec.data);return new Blob([pt],{type:rec.type})}
function icon(type){return type&&type.startsWith('image/')?'▧':'▱'}
async function render(){try{const raw=sessionStorage.getItem('auron_session_key');if(!raw)throw new Error('Kein aktiver Vault. Öffne zuerst Auron Vault und entsperre den Tresor.');let files=await all();const q=search.value.trim().toLowerCase();files=files.filter(f=>f.name.toLowerCase().includes(q)).sort((a,b)=>sortDesc?b.updatedAt-a.updatedAt:a.name.localeCompare(b.name,'de'));meta.textContent=files.length+' Datei'+(files.length===1?'':'en')+' · lokaler verschlüsselter Speicher';if(!files.length){list.innerHTML='<div class="empty"><strong>Keine Dateien</strong><span>Füge deine erste Datei hinzu.</span></div>';return}list.innerHTML='';for(const f of files){const row=document.createElement('div');row.className='row';row.innerHTML='<div class="icon">'+icon(f.type)+'</div><div class="main"><div class="name" title="'+esc(f.name)+'">'+esc(f.name)+'</div><div class="info">'+fmt(f.size)+' · '+new Date(f.updatedAt).toLocaleString('de-DE')+'</div></div><div class="actions"><button class="btn" data-dl="'+esc(f.id)+'">↓ <span class="label">Download</span></button><button class="btn danger" data-rm="'+esc(f.id)+'">× <span class="label">Löschen</span></button></div>';list.appendChild(row)}}catch(e){error.innerHTML='<div class="error">'+esc(e.message||'Dateimanager konnte nicht geladen werden.')+'</div>';list.innerHTML='';meta.textContent=''}}
async function add(files){for(const f of files){if(f.size>MAX){error.innerHTML='<div class="error">'+esc(f.name)+': maximal 200 MB.</div>';continue}try{const e=await encrypt(f);await put({id:crypto.randomUUID(),name:f.name,type:e.type,size:f.size,createdAt:Date.now(),updatedAt:Date.now(),iv:e.iv,data:e.data,folder:'root'});error.innerHTML=''}catch(e){error.innerHTML='<div class="error">'+esc(f.name+': '+(e.message||'Speichern fehlgeschlagen'))+'</div>'}}input.value='';render()}
drop.onclick=()=>input.click();input.onchange=()=>add([...input.files]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');add([...e.dataTransfer.files])};search.oninput=render;$('sort').onclick=()=>{sortDesc=!sortDesc;$('sort').textContent=sortDesc?'Zuletzt geändert':'Name A–Z';render()};list.onclick=async e=>{const dl=e.target.closest('[data-dl]'),rm=e.target.closest('[data-rm]');if(dl){try{const f=(await all()).find(x=>x.id===dl.dataset.dl);const b=await decrypt(f),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}catch(x){error.innerHTML='<div class="error">Datei konnte nicht entschlüsselt werden.</div>'}}if(rm){if(!confirm('Datei endgültig löschen?'))return;await remove(rm.dataset.rm);render()}};$('back').onclick=()=>location.href='./';render();
})();